on:
  pull_request_target:
    types: [opened]

jobs:
  post-pull-request-close:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Hi! PR will be reviewed"
